#!/bin/bash

echo "🚀 Hướng dẫn tạo GitHub repository và deploy"
echo ""
echo "1️⃣ Tạo repository GitHub:"
echo "   - Truy cập https://github.com/new"
echo "   - Repository name: google-translate-app"
echo "   - Chọn Public hoặc Private"
echo "   - KHÔNG chọn 'Initialize with README'"
echo "   - Click 'Create repository'"
echo ""
echo "2️⃣ Link repository và push:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/google-translate-app.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣ Deploy từ GitHub:"
echo "   - Truy cập https://vercel.com/dashboard"
echo "   - Click 'Add New...' → 'Project'"
echo "   - Import từ GitHub"
echo "   - Chọn repository google-translate-app"
echo "   - Deploy tự động!"
echo ""
echo "4️⃣ Thêm Environment Variables:"
echo "   - Vào Vercel Dashboard → Project → Settings → Environment Variables"
echo "   - Thêm: GOOGLE_CLOUD_API_KEY = your_api_key"
echo ""
echo "✅ Xong! Vercel sẽ auto-deploy mỗi khi bạn push code mới"